# Site Metadata
title: "Glosas Croniquenses"
program: 
url: "glosascroniquenses.github.io"
baseurl: ""

# Build Settings
incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  autores:
    output: true
    permalink: /:collection/:name/

defaults:
  -
    scope:
      path: ""
      type: autores
    values:
      layout: autore
