# Site Metadata
title: "Prueba"
program: "prueba1"
url: "https://glosascroniquenses.github.io"
baseurl: ""

# Build Settings
incremental: true
exclude:
  - Gemfile
collections:
  autores:
    output: true
    permalink: /:collection/:name/

defaults:
  -
    scope:
      path: ""
      type: autores
    values:
      layout: autore
